apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonmonitor
  labels:
    app: monitorapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitorapp
  template:
    metadata:
      labels:
        app: monitorapp
    spec:
      containers:
      - name: monitorapp
        image: prashasthnaik/nodemonitoringapp:v1
        ports:
        - containerPort: 3000
